title:            Always Create Miracles
description:      Hi, this is Phonicavi’s blogs supported by GitHub.
disqus_shortname: Phonic
reading_time:     true
words_per_minute: 200
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
url:  
# http://www.douban.com/people/phonic/

# Owner/author information
owner:
  name:           QIU Feng(Phonic)
  avatar:         avatar_hd.jpg
  bio:            “This is Phonic from Shanghai. 
Really hope you enjoy my blogs:b”
  email:          seb7phonic@outlook.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        seb7phonic
  facebook:       profile.php?id=100004371887037
  github:         Phonicavi
  stackexchange:  
  linkedin:       pub/丰-邱/b4/782/b03
  instagram:      phonicavi
  flickr:         
  tumblr:         
  # google plus id, include the '+', eg +mmistakes
  google_plus:    +111343692368280096659

# Background image to be tiled on all pages
background:  night.png

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
highlighter: pygments
markdown:    kramdown
gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]